/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RemedyRouteImport } from './routes/remedy'
import { Route as IdentifyRouteImport } from './routes/identify'
import { Route as IndexRouteImport } from './routes/index'

const RemedyRoute = RemedyRouteImport.update({
  id: '/remedy',
  path: '/remedy',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentifyRoute = IdentifyRouteImport.update({
  id: '/identify',
  path: '/identify',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/identify': typeof IdentifyRoute
  '/remedy': typeof RemedyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/identify': typeof IdentifyRoute
  '/remedy': typeof RemedyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/identify': typeof IdentifyRoute
  '/remedy': typeof RemedyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/identify' | '/remedy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/identify' | '/remedy'
  id: '__root__' | '/' | '/identify' | '/remedy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdentifyRoute: typeof IdentifyRoute
  RemedyRoute: typeof RemedyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/remedy': {
      id: '/remedy'
      path: '/remedy'
      fullPath: '/remedy'
      preLoaderRoute: typeof RemedyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identify': {
      id: '/identify'
      path: '/identify'
      fullPath: '/identify'
      preLoaderRoute: typeof IdentifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdentifyRoute: IdentifyRoute,
  RemedyRoute: RemedyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
